### ISSUE TITLE
Add 64-bit version?

### ISSUE THREAD

**Issue by neheb** [UnitedRPMs/libtxc_dxtn#1]
Steam requires the 32-bit version but some games such as dota 2 are 64-bit only and require the 64-bit version of this package.

**Comment by sergiomb2** [comment]
Hello , I'm thinking, I can't maintain rpmfusion and unitedrpms , I don't speak by others, but you should have it on RPMFusion ... hope that can help you 
Thanks, 
http://download1.rpmfusion.org/free/fedora/releases/24/Everything/x86_64/os/repoview/libtxc_dxtn.html

**Comment by paulcarroty** [comment]
@sergiomb2 @neheb it's available:

```
dnf search libtxc_dxtn
Last metadata expiration check: 0:13:05 ago on Mon Jul  4 15:49:41 2016.
=========================== N/S Matched: libtxc_dxtn ===========================
libtxc_dxtn.i686 : Free implementation of the s3tc texture compression algorithm
```

How to install:

```
# dnf install libtxc_dxtn.i686
```

**Comment by paulcarroty** [comment]
> I'm thinking, I can't maintain rpmfusion and unitedrpms

Do what you want to do© Your help here is really great, thx.

**Comment by paulcarroty** [comment]
Added.
